# Generated by Django 4.2.4 on 2023-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('name_type', models.CharField(max_length=100)),
                ('recorded_class', models.CharField(max_length=100)),
                ('discovery_type', models.CharField(max_length=100)),
            ],
        ),
    ]
